Truncate Table PS_Chatlog.dbo.ChatLog
Truncate Table PS_Billing.dbo.AuctionProductList
Truncate Table PS_Billing.dbo.Clean_AllUser2
Truncate Table PS_Billing.dbo.Clean_AllUsers
Truncate Table PS_Billing.dbo.Clean_Users_Detail
Truncate Table PS_Billing.dbo.CleanLog
Truncate Table PS_Billing.dbo.CleanSocialNo
Truncate Table PS_Billing.dbo.Considers
Truncate Table PS_Billing.dbo.EventItems
Truncate Table PS_Billing.dbo.EventUsers
Truncate Table PS_Billing.dbo.MileageEvent
Truncate Table PS_Billing.dbo.PcBangEvent
Truncate Table PS_Billing.dbo.TmpSlotError
Truncate Table PS_Billing.dbo.Users_Product
Truncate Table PS_Billing.dbo.Users_Product2
Truncate Table PS_GameData.dbo._CreatedChars
Truncate Table PS_GameData.dbo._DeletedChars
Truncate Table PS_GameData.dbo._GuildDetailsBack
Truncate Table PS_GameData.dbo._GuildRankPoint
Truncate Table PS_GameData.dbo._GuildsBack
Truncate Table PS_GameData.dbo.BanChars
Truncate Table PS_GameData.dbo.CharApplySkills
Truncate Table PS_GameData.dbo.CharBacks
Truncate Table PS_GameData.dbo.CharEvents
Truncate Table PS_GameData.dbo.CharItems
Truncate Table PS_GameData.dbo.CharQuests
Truncate Table PS_GameData.dbo.CharQuickSlotBacks
Truncate Table PS_GameData.dbo.CharQuickSlots
Truncate Table PS_GameData.dbo.CharRenameLog
Truncate Table PS_GameData.dbo.Chars
Truncate Table PS_GameData.dbo.CharSavePoint
Truncate Table PS_GameData.dbo.CharSavePointBack
Truncate Table PS_GameData.dbo.CharSkillBacks
Truncate Table PS_GameData.dbo.CharSkills
Truncate Table PS_GameData.dbo.ConsiderBank
Truncate Table PS_GameData.dbo.ConsiderInven
Truncate Table PS_GameData.dbo.EventLog_CharSkill1
Truncate Table PS_GameData.dbo.EventLog_CharSkill2
Truncate Table PS_GameData.dbo.EventLog_CharStat
Truncate Table PS_GameData.dbo.FriendChars
Truncate Table PS_GameData.dbo.GuildChars
Truncate Table PS_GameData.dbo.GuildDetails
Truncate Table PS_GameData.dbo.GuildNpcLv
Truncate Table PS_GameData.dbo.GuildRankLog
Truncate Table PS_GameData.dbo.GuildRankLog2
Truncate Table PS_GameData.dbo.Guilds
Truncate Table PS_GameData.dbo.GuildStoredItems
Truncate Table PS_GameData.dbo.HackLog
Truncate Table PS_GameData.dbo.Keeps
Truncate Table PS_GameData.dbo.Market
Truncate Table PS_GameData.dbo.MarketCharConcern
Truncate Table PS_GameData.dbo.MarketCharResultItems
Truncate Table PS_GameData.dbo.MarketCharResultItems_DelLog
Truncate Table PS_GameData.dbo.MarketCharResultMoney
Truncate Table PS_GameData.dbo.MarketCharResultMoney_DelLog
Truncate Table PS_GameData.dbo.MarketItems
Truncate Table PS_GameData.dbo.MarketItems_DelLog
Truncate Table PS_GameData.dbo.PointErrorLog
Truncate Table PS_GameData.dbo.PointGiftNotify
Truncate Table PS_GameData.dbo.PointLog
Truncate Table PS_GameData.dbo.ProductLog
Truncate Table PS_GameData.dbo.QuestAward
Truncate Table PS_GameData.dbo.TmpGuildEtin
Truncate Table PS_GameData.dbo.UserMaxGrow
Truncate Table PS_GameData.dbo.UserStoredItems
Truncate Table PS_GameData.dbo.UserStoredMoney
Truncate Table PS_GameData.dbo.UserStoredPointItems
Truncate Table PS_GameLog.dbo.ActionLog
Truncate Table PS_GameLog.dbo.ActionTypeDefs
Truncate Table PS_GameLog.dbo.UserLog
Truncate Table PS_UserData.dbo.UserBlockLog
Truncate Table PS_UserData.dbo.UserLeaveLog
Truncate Table PS_UserData.dbo.UserLoginLog
Truncate Table PS_UserData.dbo.UserLoginStatus
Truncate Table PS_UserData.dbo.UserPauseLog
Truncate Table PS_UserData.dbo.UserPointChargeLog
Truncate Table PS_UserData.dbo.Users_Block
Truncate Table PS_UserData.dbo.Users_BlockLog
Truncate Table PS_UserData.dbo.Users_Deleted
Truncate Table PS_UserData.dbo.Users_Detail
Truncate Table PS_UserData.dbo.Users_Master
Truncate Table PS_UserData.dbo.Users_Updatelog
